spring:
  profiles: local

# use local mongodb at localhost:27017

server:
  port: 8080

---

github:
  owner: ${GITHUB_OWNER}
  repositories: ${GITHUB_REPOSITORIES}
  token: ${GITHUB_TOKEN}

spring:
  profiles: production
  data:
    mongodb:
      uri: ${MONGODB_URI}

server:
  port: ${PORT}

tracker:
  project: ${TRACKER_PROJECT}
  token: ${TRACKER_TOKEN}